### ISSUE TITLE
update important feature from original repo

### ISSUE THREAD

**Issue by terion-name** [rogervila/laravel-mix-stylus#3]
please merge this:
https://github.com/JeffreyWay/laravel-mix/issues/304

**Comment by rogervila** [comment]
Hi, for now I'm cloning every laravel-mix version. 

Jefrey says that he will merge it on the next version, then I will adapt it again with default stylus support.

**Comment by terion-name** [comment]
@rogervila ok, thanx. point your attention jut in case )
